# Generated by Django 4.2.11 on 2025-01-28 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the degree', max_length=255)),
            ],
            options={
                'verbose_name': 'Degree',
                'verbose_name_plural': 'Degrees',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the theme', max_length=255)),
                ('primary_color', models.CharField(default='#007BFF', help_text='Primary color in HEX.', max_length=7)),
                ('secondary_color', models.CharField(default='#6C757D', help_text='Secondary color in HEX.', max_length=7)),
                ('tertiary_color', models.CharField(default='#F8F9FA', help_text='Tertiary color in HEX.', max_length=7)),
                ('accent_success', models.CharField(default='#28A745', help_text='Accent color for success.', max_length=7)),
                ('accent_warning', models.CharField(default='#FFC107', help_text='Accent color for warnings.', max_length=7)),
                ('accent_error', models.CharField(default='#DC3545', help_text='Accent color for errors.', max_length=7)),
                ('header_font', models.CharField(default='Arial', help_text='Header font family.', max_length=100)),
                ('body_font', models.CharField(default='Roboto', help_text='Body font family.', max_length=100)),
                ('background_color', models.CharField(default='#0E1924', help_text='Background color in HEX.', max_length=7)),
                ('card_background', models.CharField(default='#FFFFFF', help_text='Card background color in HEX.', max_length=7)),
                ('text_color', models.CharField(default='#292E4A', help_text='Text color in HEX.', max_length=7)),
                ('highlight_color', models.CharField(default='#FF6600', help_text='Highlight color in HEX.', max_length=7)),
                ('shadow_color', models.CharField(default='rgba(0, 0, 0, 0.15)', help_text='Shadow color in RGBA.', max_length=50)),
                ('shadow_hover_color', models.CharField(default='rgba(0, 0, 0, 0.25)', help_text='Shadow hover color in RGBA.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the theme was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the theme was last updated.')),
            ],
            options={
                'verbose_name': 'Theme',
                'verbose_name_plural': 'Themes',
            },
        ),
        migrations.CreateModel(
            name='Branding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(default='My Institute', help_text='The name of the institute.', max_length=255)),
                ('favicon', models.ImageField(blank=True, help_text='Upload the favicon/icon.', null=True, upload_to='branding/icons/')),
                ('login_background', models.ImageField(blank=True, help_text='Upload the login page background.', null=True, upload_to='branding/backgrounds/')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last updated timestamp.')),
                ('theme', models.ForeignKey(blank=True, help_text='The selected theme for the branding.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brandings', to='branding.theme')),
            ],
            options={
                'verbose_name': 'Branding Settings',
                'verbose_name_plural': 'Branding Settings',
            },
        ),
    ]
