# Generated by Django 5.1.4 on 2024-12-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branding',
            options={'verbose_name': 'Branding Settings', 'verbose_name_plural': 'Branding Settings'},
        ),
        migrations.RemoveField(
            model_name='branding',
            name='cover_photo_path',
        ),
        migrations.RemoveField(
            model_name='branding',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='branding',
            name='favicon_path',
        ),
        migrations.RemoveField(
            model_name='branding',
            name='institution_name',
        ),
        migrations.RemoveField(
            model_name='branding',
            name='logo_path',
        ),
        migrations.AddField(
            model_name='branding',
            name='accent_error',
            field=models.CharField(default='#DC3545', help_text='Accent color for error messages.', max_length=7),
        ),
        migrations.AddField(
            model_name='branding',
            name='accent_success',
            field=models.CharField(default='#28A745', help_text='Accent color for success messages.', max_length=7),
        ),
        migrations.AddField(
            model_name='branding',
            name='accent_warning',
            field=models.CharField(default='#FFC107', help_text='Accent color for warning messages.', max_length=7),
        ),
        migrations.AddField(
            model_name='branding',
            name='body_font',
            field=models.CharField(default='Roboto', help_text='Font family for body text.', max_length=100),
        ),
        migrations.AddField(
            model_name='branding',
            name='custom_css',
            field=models.TextField(blank=True, help_text='Custom CSS to override styles.'),
        ),
        migrations.AddField(
            model_name='branding',
            name='custom_js',
            field=models.TextField(blank=True, help_text='Custom JavaScript for advanced customization.'),
        ),
        migrations.AddField(
            model_name='branding',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Upload the favicon/icon.', null=True, upload_to='branding/icons/'),
        ),
        migrations.AddField(
            model_name='branding',
            name='footer_text',
            field=models.TextField(blank=True, help_text='Custom footer text.'),
        ),
        migrations.AddField(
            model_name='branding',
            name='header_font',
            field=models.CharField(default='Arial', help_text='Font family for headers.', max_length=100),
        ),
        migrations.AddField(
            model_name='branding',
            name='institute_name',
            field=models.CharField(default='My Institute', help_text='The name of the institute.', max_length=255),
        ),
        migrations.AddField(
            model_name='branding',
            name='login_background',
            field=models.ImageField(blank=True, help_text='Upload the login page background.', null=True, upload_to='branding/backgrounds/'),
        ),
        migrations.AddField(
            model_name='branding',
            name='primary_color',
            field=models.CharField(default='#007BFF', help_text='Primary color in HEX.', max_length=7),
        ),
        migrations.AddField(
            model_name='branding',
            name='secondary_color',
            field=models.CharField(default='#6C757D', help_text='Secondary color in HEX.', max_length=7),
        ),
        migrations.AddField(
            model_name='branding',
            name='tertiary_color',
            field=models.CharField(default='#F8F9FA', help_text='Tertiary color in HEX.', max_length=7),
        ),
        migrations.AlterField(
            model_name='branding',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last updated timestamp.'),
        ),
    ]
