# Generated by Django 5.1.4 on 2025-01-05 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0003_degree'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the theme', max_length=100, unique=True)),
                ('primary_color', models.CharField(help_text='Primary color in HEX.', max_length=7)),
                ('secondary_color', models.CharField(help_text='Secondary color in HEX.', max_length=7)),
                ('tertiary_color', models.CharField(help_text='Tertiary color in HEX.', max_length=7)),
                ('accent_success', models.CharField(help_text='Accent color for success messages.', max_length=7)),
                ('accent_warning', models.CharField(help_text='Accent color for warning messages.', max_length=7)),
                ('accent_error', models.CharField(help_text='Accent color for error messages.', max_length=7)),
                ('header_font', models.CharField(default='Arial', help_text='Font family for headers.', max_length=100)),
                ('body_font', models.CharField(default='Roboto', help_text='Font family for body text.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the theme was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the theme was last updated.')),
            ],
            options={
                'verbose_name': 'Theme',
                'verbose_name_plural': 'Themes',
            },
        ),
        migrations.AlterModelOptions(
            name='degree',
            options={'verbose_name': 'Degree', 'verbose_name_plural': 'Degrees'},
        ),
        migrations.RemoveField(
            model_name='branding',
            name='accent_error',
        ),
        migrations.RemoveField(
            model_name='branding',
            name='accent_success',
        ),
        migrations.RemoveField(
            model_name='branding',
            name='accent_warning',
        ),
        migrations.RemoveField(
            model_name='branding',
            name='body_font',
        ),
        migrations.RemoveField(
            model_name='branding',
            name='custom_css',
        ),
        migrations.RemoveField(
            model_name='branding',
            name='custom_js',
        ),
        migrations.RemoveField(
            model_name='branding',
            name='footer_text',
        ),
        migrations.RemoveField(
            model_name='branding',
            name='header_font',
        ),
        migrations.RemoveField(
            model_name='branding',
            name='primary_color',
        ),
        migrations.RemoveField(
            model_name='branding',
            name='secondary_color',
        ),
        migrations.RemoveField(
            model_name='branding',
            name='tertiary_color',
        ),
        migrations.AddField(
            model_name='branding',
            name='theme',
            field=models.ForeignKey(blank=True, help_text='The selected theme for the branding.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brandings', to='branding.theme'),
        ),
    ]
