# Generated by Django 5.1.4 on 2025-01-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0004_theme_alter_degree_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='background_color',
            field=models.CharField(default='#0E1924', help_text='Background color in HEX.', max_length=7),
        ),
        migrations.AddField(
            model_name='theme',
            name='card_background',
            field=models.CharField(default='#FFFFFF', help_text='Card background color in HEX.', max_length=7),
        ),
        migrations.AddField(
            model_name='theme',
            name='highlight_color',
            field=models.CharField(default='#FF6600', help_text='Highlight color in HEX.', max_length=7),
        ),
        migrations.AddField(
            model_name='theme',
            name='shadow_color',
            field=models.CharField(default='rgba(0, 0, 0, 0.15)', help_text='Shadow color in RGBA.', max_length=50),
        ),
        migrations.AddField(
            model_name='theme',
            name='shadow_hover_color',
            field=models.CharField(default='rgba(0, 0, 0, 0.25)', help_text='Shadow hover color in RGBA.', max_length=50),
        ),
        migrations.AddField(
            model_name='theme',
            name='text_color',
            field=models.CharField(default='#292E4A', help_text='Text color in HEX.', max_length=7),
        ),
        migrations.AlterField(
            model_name='theme',
            name='accent_error',
            field=models.CharField(default='#DC3545', help_text='Accent color for errors.', max_length=7),
        ),
        migrations.AlterField(
            model_name='theme',
            name='accent_success',
            field=models.CharField(default='#28A745', help_text='Accent color for success.', max_length=7),
        ),
        migrations.AlterField(
            model_name='theme',
            name='accent_warning',
            field=models.CharField(default='#FFC107', help_text='Accent color for warnings.', max_length=7),
        ),
        migrations.AlterField(
            model_name='theme',
            name='body_font',
            field=models.CharField(default='Roboto', help_text='Body font family.', max_length=100),
        ),
        migrations.AlterField(
            model_name='theme',
            name='header_font',
            field=models.CharField(default='Arial', help_text='Header font family.', max_length=100),
        ),
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(help_text='Name of the theme', max_length=255),
        ),
        migrations.AlterField(
            model_name='theme',
            name='primary_color',
            field=models.CharField(default='#007BFF', help_text='Primary color in HEX.', max_length=7),
        ),
        migrations.AlterField(
            model_name='theme',
            name='secondary_color',
            field=models.CharField(default='#6C757D', help_text='Secondary color in HEX.', max_length=7),
        ),
        migrations.AlterField(
            model_name='theme',
            name='tertiary_color',
            field=models.CharField(default='#F8F9FA', help_text='Tertiary color in HEX.', max_length=7),
        ),
    ]
