# Generated by Django 5.1.4 on 2025-01-09 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0005_theme_background_color_theme_card_background_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='degree',
            name='branding',
        ),
    ]
