# Generated by Django 4.2.11 on 2025-01-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Anonymous User', max_length=255)),
                ('field_of_study', models.CharField(default='Bsc Computer Science major in Software Engineering', max_length=255)),
                ('student_id', models.CharField(default=0, max_length=20)),
                ('content', models.TextField()),
                ('rating', models.IntegerField()),
                ('sentiment', models.CharField(blank=True, max_length=10, null=True)),
                ('admin_response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sentiment_details', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
