# Generated by Django 5.1.4 on 2025-01-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='admin_response',
            field=models.TextField(blank=True, help_text="Admin's response to the feedback.", null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='sentiment',
            field=models.CharField(blank=True, help_text='Sentiment analysis result (e.g., positive, negative, neutral).', max_length=20, null=True),
        ),
    ]
