# Generated by Django 5.1.4 on 2025-01-18 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_feedback_admin_response_alter_feedback_content_and_more'),
        ('rooms', '0006_remove_room_image_path_room_image_room_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='field_of_study',
            field=models.CharField(default='Bsc Computer Science major in Software Engineering', max_length=255),
        ),
        migrations.AddField(
            model_name='feedback',
            name='full_name',
            field=models.CharField(default='Anonymous User', max_length=255),
        ),
        migrations.AddField(
            model_name='feedback',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.room'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='student_id',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
