# Generated by Django 5.1.4 on 2024-12-22 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0006_remove_room_image_path_room_image_room_is_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_bookings', models.IntegerField(default=0)),
                ('total_checkins', models.IntegerField(default=0)),
                ('total_cancellations', models.IntegerField(default=0)),
                ('total_usage_time', models.FloatField(default=0.0)),
                ('peak_hours', models.JSONField(default=dict)),
                ('utilization_rate', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='rooms.room')),
            ],
        ),
    ]
