# Generated by Django 4.2.11 on 2025-01-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_bookings', models.IntegerField(default=0)),
                ('total_checkins', models.IntegerField(default=0)),
                ('total_cancellations', models.IntegerField(default=0)),
                ('total_usage_time', models.FloatField(default=0.0)),
                ('peak_hours', models.JSONField(default=dict)),
                ('utilization_rate', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
