# Generated by Django 5.1.4 on 2024-12-28 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytics',
            name='date',
            field=models.DateField(),
        ),
    ]
