# Generated by Django 5.1.4 on 2025-01-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('rooms', '0006_remove_room_image_path_room_image_room_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='analytics',
            constraint=models.UniqueConstraint(fields=('room', 'date'), name='unique_room_date_analytics'),
        ),
    ]
