# Generated by Django 5.1.4 on 2025-01-22 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_analytics_unique_room_date_analytics'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='analytics',
            name='unique_room_date_analytics',
        ),
    ]
