# Generated by Django 5.1.4 on 2025-01-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_remove_analytics_unique_room_date_analytics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytics',
            name='date',
            field=models.DateField(),
        ),
    ]
