# Generated by Django 5.1.4 on 2025-01-23 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_analytics_date'),
        ('analytics', '0004_alter_analytics_date'),
    ]

    operations = [
    ]
