# Generated by Django 4.2.11 on 2025-01-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('checked_in', 'Checked In'), ('canceled', 'Canceled'), ('checked_out', 'Checked Out')], default='pending', max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('penalty_flag', models.BooleanField(default=False)),
                ('checked_in', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('degree_major', models.TextField(blank=True, null=True)),
                ('purpose', models.TextField(default='N/A')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
