# Generated by Django 5.1.4 on 2025-01-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('checked_in', 'Checked In'), ('canceled', 'Canceled'), ('checked_out', 'Checked Out')], default='pending', max_length=20),
        ),
    ]
