# Generated by Django 5.1.4 on 2024-12-31 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_price'),
        ('branding', '0003_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='degree_major',
            field=models.ForeignKey(blank=True, help_text='Degree associated with the booking.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branding.degree'),
        ),
        migrations.AddField(
            model_name='booking',
            name='purpose',
            field=models.TextField(default='N/A', help_text='Detailed purpose for the booking.'),
            preserve_default=False,
        ),
    ]
