# Generated by Django 5.1.4 on 2025-01-17 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_degree_major_booking_purpose'),
        ('branding', '0006_remove_degree_branding'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={},
        ),
        migrations.AlterField(
            model_name='booking',
            name='degree_major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branding.degree'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='purpose',
            field=models.TextField(),
        ),
    ]
