# Generated by Django 5.1.4 on 2025-01-24 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_booking_options_alter_booking_degree_major_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['start_time']},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='degree_major',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='purpose',
        ),
    ]
