# Generated by Django 5.1.4 on 2025-01-24 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_status'),
        ('bookings', '0007_alter_booking_options_remove_booking_degree_major_and_more'),
    ]

    operations = [
    ]
