# Generated by Django 5.1.4 on 2025-01-25 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_merge_20250124_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='degree_major',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='purpose',
            field=models.TextField(default='N/A'),
        ),
    ]
