# Generated by Django 5.1.4 on 2025-01-24 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_room_description_room_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='features',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
