# Generated by Django 5.1.4 on 2025-01-13 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userprofile_alter_customuser_options_and_more'),
    ]

