# Generated by Django 5.1.4 on 2025-01-22 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_customuser_first_name_and_more'),
    ]


    operations = [
    ]
