# Generated by Django 5.1.4 on 2025-01-22 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '00013_remove_customuser_first_name_and_more'),
        ('users', '0012_merge_20250122_1648'),
    ]

    operations = [
    ]
