# Generated by Django 5.1.4 on 2024-12-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking_update', 'Booking Update'), ('penalty_reminder', 'Penalty Reminder'), ('general', 'General'), ('admin_alert', 'Admin Alert')], default='general', max_length=50),
        ),
    ]
