# Generated by Django 5.1.4 on 2025-01-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penalties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penalty',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=10),
        ),
    ]
