# Generated by Django 5.1.4 on 2025-01-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penalties', '0002_alter_penalty_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penalty',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('review_requested', 'Review Requested')], default='unpaid', max_length=20),
        ),
    ]
